# Static HTML site configuration
[build]
  publish = "."
  command = "echo 'Static site - no build required'"

# SPA fallback for client-side routing (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
